export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const GET_IMG = 'GET_IMG'
export const UPLOAD_IMG = "UPLOAD_IMG"

// for form Input

export const NAME_INPUT = "NAME_INPUT"
export const EMAIL_INPUT = "EMAIL_INPUT"
export const COMPANY_INPUT = "COMPANY_INPUT"
export const ADDRESS_INPUT = "ADDRESS_INPUT"
export const PHONE_NO_INPUT = "PHONE_NO_INPUT"
